export const actionTypes = {
    ADD_TODO : "ADD_TODO",
    DELETE_TODO : "DELETE_TODO",
    UPDATE_TODO : "UPDATE_TODO",
    RESET_TODOS : "RESET_TODOS",
    ADD_CART : "ADD_CART",
    ADD_EXPENSE:"ADD_EXPENSE",
    DELETE_EXPENSE:"DELETE_EXPENSE",
    UPDATE_EXPENSE:"UPDATE_EXPENSE",
    RSSET_EXPENSE:"RESET_EXPENSE",
}